'use strict';

const SOURCES = Object.freeze(['REFERRAL', 'INTERNAL', 'JOB_BOARD', 'OTHER']);

const APPLICATION_STATUS = Object.freeze({
  RECEIVED: 'RECEIVED',
  IN_REVIEW: 'IN_REVIEW',
  REJECTED: 'REJECTED',
  HIRED: 'HIRED',
});
const APPLICATION_STATUSES = Object.freeze(Object.values(APPLICATION_STATUS));
const ACTIVE_STATUSES = Object.freeze([APPLICATION_STATUS.RECEIVED, APPLICATION_STATUS.IN_REVIEW]);
const FINAL_STATUSES = Object.freeze([APPLICATION_STATUS.REJECTED, APPLICATION_STATUS.HIRED]);

const VACANCY_STATUS = Object.freeze({ OPEN: 'OPEN', CLOSED: 'CLOSED' });

const PRIORITY = Object.freeze({ LOW: 'LOW', MEDIUM: 'MEDIUM', HIGH: 'HIGH', TOP: 'TOP' });

const REAPPLY_WAIT_DAYS = 30;

module.exports = {
  SOURCES,
  APPLICATION_STATUS,
  APPLICATION_STATUSES,
  ACTIVE_STATUSES,
  FINAL_STATUSES,
  VACANCY_STATUS,
  PRIORITY,
  REAPPLY_WAIT_DAYS,
};
